Added Skeleton for Books
Maruf-co/Macrofront pull request #2
Opened 2023-03-25 11:38 UTC by PlutoEx

2023-03-25 12:15 UTC, Maruf-co requested changes

2023-03-25 12:15 UTC, Maruf-co commented on src/app.tsx
> -import { Button } from "./components/Button";
Не юзается, можно убрать

2023-03-25 12:15 UTC, Maruf-co commented on src/components/Book/Book.tsx
> +import {ModalContentStyles, ModalStyles, scrollbarStyle, TextStyle} from "./Book.styles";
Оно же не юзается ниже, не?

2023-03-25 12:15 UTC, Maruf-co commented on src/components/Book/Book.tsx
> +import styled from "@emotion/styled";
7-8 строчка тоже.

2023-03-25 12:15 UTC, Maruf-co commented on src/components/Book/Book.tsx
> +        const fetchBookInfo = async () => {
Кажется лучше выносить логику в отдельные функции, нужно стараться разделять визуал и работу с серваком.

2023-03-25 12:15 UTC, Maruf-co commented on src/components/Book/Book.tsx
> +    const customStyles = {
Стили лучше держать в файле для стилей (Book.styles.ts)

2023-03-25 12:15 UTC, Maruf-co commented on src/components/Book/Book.tsx
> +                    authors: bookData.details.authors ? bookData.details.authors.map((author: any) => author.name) : null,
использование any в ts - плохая практика

2023-03-25 12:15 UTC, Maruf-co commented on src/components/Book/Book.tsx
> +                    languages: bookData.details.languages ? bookData.details.languages.map((lang: any) => lang.key) : null,
any :(

2023-03-25 12:15 UTC, Maruf-co commented on src/components/Book/Book.tsx
> +                    coverUrl: bookData.details.covers ? `https://covers.openlibrary.org/b/id/${bookData.details.covers[0]}-L.jpg` : null,
А почему ты в строчках 61-73 юзаешь || null ?

Не легче тогда дефолтно задать всем полям null? (строки 36-49)

2023-03-25 12:15 UTC, Maruf-co commented on src/components/Book/Book.tsx
> +            <h2 style={{fontFamily: "Russo One"}}>{bookInfo.title}</h2>
использовать inline стили (style= ...) - плохая практика. Лучше выносить в какой-то className. Пример:
`<h2 className='title'>{bookInfo.title}</h2>`

И уже внутри файла стилей:

```
.title {
    fontFamily: "Russo One"
}
```


Правда у нас emotion, надо б чекнуть как там classnames прописываются.

2023-03-25 12:15 UTC, Maruf-co commented on src/components/Book/Book.tsx
> +            <div style={{display: "flex", alignItems: "center", margin: "20px 0"}}>
inline styles :(

2023-03-25 12:15 UTC, Maruf-co commented on src/components/Book/Book.tsx
> +                        style={{marginRight: "20px",
inline styles :(

2023-03-25 12:15 UTC, Maruf-co commented on src/components/Book/Book.tsx
> +                    {bookInfo.sub_title && <p style={TextStyle}>{bookInfo["sub_title"]}</p>}
О, вот тут ты уже иначе делаешь. Я видел ты где-то ещё через css стили задаёшь?

Надо б на чём-то одном остановиться (но задавать через style не оч)

2023-03-25 12:15 UTC, Maruf-co commented on src/components/Book/Book.tsx
> +            <button onClick={handleClose} style={{
inline styles :(

Не стану под каждым оставлять, ты понял короче)

2023-03-25 12:15 UTC, Maruf-co commented on src/components/Book/Books.tsx
> +import React, {useState} from 'react';
Предлагаю вынести всё это в отдельный компонент Books. Нужно всё декомпозировать настолько детально, наскок можем (до атомарных уровней) 
Так легче тестировать, разбираться в маленьких файлах нежели огромных и переиспользовать компоненты

2023-03-25 12:15 UTC, Maruf-co commented on src/components/Book/Books.tsx
> +import {jsx, css} from "@emotion/react";
ненужные импорты

2023-03-25 12:15 UTC, Maruf-co commented on src/components/Book/Books.tsx
> +import Modal from "react-modal";
ненужные импорты

2023-03-25 12:15 UTC, Maruf-co commented on src/components/Book/Books.tsx
> +                        <strong css={TextStyle} style={{fontSize: '10px'}}>{book.title}</strong>
тут юзаешь и css и style, не оч так делать(

Вопрос на рисёрч. Ты по идее больше нас с Тимой повзаимодействал с emotion наверн. 
Какой единый элемент задавания стилей мы можем юзать? Что такое css? Почему не className или в emotion так не получится?
Отпиши в тг плез. Будем придерживаться стандарта.

2023-03-25 12:15 UTC, Maruf-co commented on src/components/Book/BooksSearch.tsx
> +import React, {useState} from 'react';
Отдельный компонент

2023-03-25 12:15 UTC, Maruf-co commented on src/components/Book/BooksSearch.tsx
> +import {jsx, css} from "@emotion/react";
не юзаются импорты.
Кста. Могу ошибаться и выше ошибся мб. Отпиши где оно юзается? Мой эдитор их неиспользуемыми показывает.

2023-03-25 12:15 UTC, Maruf-co commented on src/components/Book/BooksSearch.tsx
> +    const handleSearch = async (e: React.FormEvent<HTMLFormElement>) => {
Вынести логику отдельно.

2023-03-25 12:15 UTC, Maruf-co commented on src/components/Input/index.tsx
> +type InputProps = {
Где-то юзаешь interface. где-то type. Давай одно или почему тут именно type?

2023-03-25 12:15 UTC, Maruf-co commented on src/components/Input/index.tsx
> +import React, {useState} from 'react';
Вынес в отдельный компонент, харош)
Правда не хватает файла .stories.tsx :( шоб в сторибуке оценивать компоненты.

Вдохновляйся как сделан Button. Нам нужна единая структура компонентов:
 `Button.stories.tsx` - пример компонента для сторибука
 `Button.styles.ts` - стили
`types.ts` - интерфейсы
 `index.tsx` - сам компонент использующий предыдущие 2 штуки

2023-04-11 11:25 UTC, PlutoEx commented on src/components/Book/Books.tsx
> +import React, {useState} from 'react';
Разделить Book? уже есть 3 компонента Book - модалка, Books - Выводит карточки книжек с минимумом садержания,  BooksSearch - Поисковая строка

2023-04-11 11:33 UTC, PlutoEx commented on src/components/Book/BooksSearch.tsx
> +import {jsx, css} from "@emotion/react";
/** @jsx jsx */
import {jsx, css} from "@emotion/react";
Без этого css=SomeCss не робит

2023-04-11 11:37 UTC, PlutoEx commented on src/components/Input/index.tsx
> +import React, {useState} from 'react';
все еще не понимаю что за сторибук и зачем он)

2023-04-11 11:51 UTC, Maruf-co commented on src/components/Book/Books.tsx
> +import React, {useState} from 'react';
Компонент это не просто .tsx файл, а отдельные стили, константы, интерфейсы, вспомогательные функции, например. И когда оно всё соединено в одном, то может быть очень сложно потом модифицировать компонент и ориентироваться в нём в будущем, покрывать тестами.
Вообще если набор компонентов является составляющими другого крупного компонента и используются, токо в нём, то можно допустим внутри папки Book засунуть папки и BookSearch и т.д.

2023-04-11 11:56 UTC, Maruf-co commented on src/components/Input/index.tsx
> +import React, {useState} from 'react';
Сторибук это тупо хранилище всех наших компонентов.
В крупных проектах бывает оч полезен, когда этих компонентов у нас сотни и легче визуально из искать, тыкать в разные пропсы нежели просто смотреть в код или искать конкретные компоненты на всём запущенном проекте.

В данном случае нас в тз просят добавлять компоненты в сторибук (data visualization lib чтоле)

2023-04-11 11:57 UTC, Maruf-co commented on src/components/Input/index.tsx
> +import React, {useState} from 'react';
Но я чекну ка.
Если можно без, то чилл))

2023-04-22 06:21 UTC, Maruf-co approved these changes

2023-04-26 14:49 UTC, merged